version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli typescript

  pre_build:
    commands:
      - echo Entering pre-build stage
      - echo Nothing to do in pre-build
      - echo Exiting pre-build stage
  build:
    commands:
      - echo Entering build stage
      - echo Building API
      - cd $CODEBUILD_SRC_DIR/api
      - npm install
      - npm run build
      - echo Building UI
      - cd $CODEBUILD_SRC_DIR/appekko-ui
      - npm install
      - npm run build --prod
      - echo Exiting build stage
  post_build:
    commands:
      - echo Entering post-build stage
      - echo Nothing to do in post-build
      - echo Exiting post-build stage
artifacts:
  files:
    - dist/**/*
    - package.json
    - node_modules/**/*